services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - FINERACT_BASE_URL=${FINERACT_BASE_URL}
      - FINERACT_TENANT=${FINERACT_TENANT}
      - FINERACT_USERNAME=${FINERACT_USERNAME}
      - FINERACT_PASSWORD=${FINERACT_PASSWORD}
