services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - FINERACT_BASE_URL=${FINERACT_BASE_URL}
      - FINERACT_TENANT=${FINERACT_TENANT}
      - FINERACT_USERNAME=${FINERACT_USERNAME}
      - FINERACT_PASSWORD=${FINERACT_PASSWORD}
      - DB_URI=host=postgres user=postgres password=postgres dbname=openbank port=5432 sslmode=disable

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openbank
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
