services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - MONGODB_URI=mongodb://root:neobank!2025@mongo:27017

  mongo:
    image: mongo:8.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: neobank!2025
    volumes:
      - ./mongodb-data:/data/db