version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: openbank
      MONGO_INITDB_ROOT_PASSWORD: openbank
      MONGO_INITDB_DATABASE: openbank
    ports:
      - 27017:27017
    volumes:
      - ../tmp/mongodb:/data/db