version: '3.8'

services:
  openbank-api:
    image: openbank-api
    build:
      context: "../"
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - MONGODB_URI=mongodb://openbank:openbank@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: openbank
      MONGO_INITDB_ROOT_PASSWORD: openbank
      MONGO_INITDB_DATABASE: openbank
    ports:
      - 27017:27017
    volumes:
      - ../tmp/mongodb:/data/db